### ISSUE TITLE
目前项目是否是完整的

### ISSUE THREAD

**Issue by youcyousyunn** [codedrinker/community#1]
你好， 今天我下载了项目，发现很多地方都是有错误的比如：AccessTokenDTO中字段并没有get和set方法，而在AuthorizeController.java中callback方法中却调用了AccessTokenDTO类的set方法

**Comment by valleyk** [comment]
lombok插件，不用手写get.set

**Comment by youcyousyunn** [comment]
Thanks 孤陋寡闻了 抱拳
