### ISSUE TITLE
Github OAuth

### ISSUE THREAD

**Issue by DustMerlin** [codedrinker/community#30]
github官方文档里的，授权登录的页面好像访问不了，这是怎么回事，是我弄错了吗？？？

**Comment by DustMerlin** [comment]
https://github.com/login/oauth/authorize 文档里给的是这个，页面显示404

**Comment by lionng** [comment]
> https://github.com/login/oauth/authorize 文档里给的是这个，页面显示404

https://docs.github.com/en/developers/apps/creating-an-oauth-app 这个是github授权的官方文档，仔细阅读步骤，看up主的讲解，github页面有更新，但是内容没变动啊，只是增加了新功能。看文档，而不是想当然的访问一个网页能不能打开，得看上下文啊，兄弟!
