### ISSUE TITLE
要部署服务器吗，我这爆500了

### ISSUE THREAD

**Issue by LiviMava** [codedrinker/community#34]
![issue](https://user-images.githubusercontent.com/53635704/97111453-d3cd4b00-1719-11eb-90e4-e5a555ee2001.png)

**Comment by sdzy9412** [comment]
你后来解决了吗 是什么导致这个问题的啊？

**Comment by Venlafaxine** [comment]
就是数据库没部署好 看一下下一段朋友。

-------------------------------------------------------------
资源文件
未使用 Flyway 之前的数据库脚本

CREATE TABLE USER
(
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
    TOKEN VARCHAR(36),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT
);
运行 migrate 和 generator 的命令

mvn flyway:migrate
mvn -Dmybatis.generator.overwrite=true mybatis-generator:generate

**Comment by sdzy9412** [comment]
非常感谢！
